SDSExam_Penote/Models/RecyclableItem.cs
using System.ComponentModel.DataAnnotations;

namespace SDSExam_Penote.Models
{
    public class RecyclableItem
    {
        public int Id { get; set; }

        [Required]
        public int RecyclableTypeId { get; set; }

        [Required, Range(0.01, double.MaxValue)]
        public decimal Weight { get; set; }

        [Display(Name = "Computed Rate")]
        public decimal ComputedRate { get; set; }

        [Required, StringLength(150)]
        public string ItemDescription { get; set; }

        public RecyclableType RecyclableType { get; set; }
    }
}

SDSExam_Penote/Controllers/RecyclableItemController.cs
using System.Net;
using System.Web.Mvc;
using SDSExam_Penote.Models;

namespace SDSExam_Penote.Controllers
{
    public class RecyclableItemController : Controller
    {
        private RecyclableItemDAL dal = new RecyclableItemDAL();

        public ActionResult Index()
        {
            return View(dal.GetAll());
        }

        public ActionResult Create()
        {
            var typeDal = new RecyclableTypeDAL();
            var recyclableTypes = typeDal.GetAll();

            ViewBag.RecyclableTypes = new SelectList(recyclableTypes, "Id", "Type");

            var model = new RecyclableItem();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecyclableItem rt)
        {
            if (ModelState.IsValid)
            {
                dal.InsertRecyclableItem(rt);
                return RedirectToAction("Index");
            }

            var typeDal = new RecyclableTypeDAL();
            var recyclableTypes = typeDal.GetAll();
            ViewBag.RecyclableTypes = new SelectList(recyclableTypes, "Id", "Type");

            return View(rt);
        }

        public ActionResult Edit(int id)
        {
            var item = dal.GetById(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            var typeDal = new RecyclableTypeDAL();
            var recyclableTypes = typeDal.GetAll();
            ViewBag.RecyclableTypes = new SelectList(recyclableTypes, "Id", "Type", item.RecyclableTypeId);

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecyclableItem item)
        {
            if (ModelState.IsValid)
            {
                dal.UpdateRecyclableItem(item);
                return RedirectToAction("Index");
            }

            var typeDal = new RecyclableTypeDAL();
            var recyclableTypes = typeDal.GetAll();
            ViewBag.RecyclableTypes = new SelectList(recyclableTypes, "Id", "Type", item.RecyclableTypeId);

            return View(item);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var rt = dal.GetById(id.Value);
            if (rt == null) return HttpNotFound();
            return View(rt);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            dal.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SDSExam_Penote/Controllers/RecyclableTypeController.cs
using System.Net;
using System.Web.Mvc;
using SDSExam_Penote.Models;

namespace SDSExam_Penote.Controllers
{
    public class RecyclableTypeController : Controller
    {
        private RecyclableTypeDAL dal = new RecyclableTypeDAL();

        public ActionResult Index()
        {
            return View(dal.GetAll());
        }

        public ActionResult Create()
        {
            var model = new RecyclableType();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] 
        public ActionResult Create(RecyclableType rt)
        {
            if (ModelState.IsValid)
            {
                dal.Insert(rt);
                return RedirectToAction("Index");
            }
            return View(rt);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var rt = dal.GetById(id.Value);
            if (rt == null) return HttpNotFound();
            return View(rt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecyclableType rt)
        {
            if (ModelState.IsValid)
            {
                dal.Update(rt);
                return RedirectToAction("Index");
            }
            return View(rt);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var rt = dal.GetById(id.Value);
            if (rt == null) return HttpNotFound();
            return View(rt);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            dal.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SDSExam_Penote/Views/RecyclableItem/Create.cshtml
@model SDSExam_Penote.Models.RecyclableItem
@{
    ViewBag.Title = "Recyclable Item";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group">
        <label>Recyclable Type</label>
        @Html.DropDownListFor(model => model.RecyclableTypeId, (SelectList)ViewBag.RecyclableTypes, "Select Type", new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Item Description</label>
        @Html.TextBoxFor(model => model.ItemDescription, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Weight)
        @Html.TextBoxFor(model => model.Weight, new { @class = "form-control", @id = "weight" })
    </div>

@*    <div class="form-group">
        <label>Computed Rate</label>
        <input type="text" id="computedRate" class="form-control" readonly />
    </div>*@


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}


@*@section Scripts {
    <script>
        let typeRates = @Html.Raw(Json.Encode(ViewBag.RecyclableTypesJson));

        function computeRate() {
            let typeId = parseInt($('#RecyclableTypeId').val());
            let weight = parseFloat($('#weight').val());

            if (!isNaN(typeId) && !isNaN(weight)) {
                let selectedType = typeRates.find(x => x.Id === typeId);

                if (selectedType) {
                    if (weight < selectedType.MinKg || weight > selectedType.MaxKg) {
                        alert(`Weight must be between ${selectedType.MinKg} and ${selectedType.MaxKg}`);
                        $('#weight').val('');
                        $('#computedRate').val('');
                    } else {
                        let computed = weight * selectedType.Rate;
                        $('#computedRate').val(computed.toFixed(2));
                    }
                }
            } else {
                $('#computedRate').val('');
            }
        }

        $(document).ready(function () {
            $('#RecyclableTypeId, #weight').on('change keyup', computeRate);
        });
    </script>
}
*@

SDSExam_Penote/Views/RecyclableItem/Delete.cshtml
@model SDSExam_Penote.Models.RecyclableItem

<h2>Are you sure you want to delete this?</h2>

<dl class="dl-horizontal">
    <dt>Type</dt>
    <dd>@Model.RecyclableTypeId</dd>

    <dt>Description</dt>
    <dd>@Model.ItemDescription</dd>

    <dt>Weight</dt>
    <dd>@Model.Weight</dd>

    <dt>Computed Rate</dt>
    <dd>@Model.ComputedRate</dd>
</dl>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <input type="submit" value="Delete" class="btn btn-danger" />
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

SDSExam_Penote/Views/RecyclableItem/Edit.cshtml
@model SDSExam_Penote.Models.RecyclableItem

@{
    ViewBag.Title = "Edit Recyclable Item";
}

<h2>Edit Recyclable Type</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true)

        @Html.Partial("_RecyclableItemForm", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

SDSExam_Penote/Views/RecyclableItem/Index.cshtml
@model IEnumerable<SDSExam_Penote.Models.RecyclableItem>

@{
    ViewBag.Title = "Recyclable Items";
}

<h2>Recyclable Items</h2>

<p>
    @Html.ActionLink("Add New", "Create")
</p>

<p>
    @Html.ActionLink("Add Recyclable Type", "Create", "RecyclableType", null, new { @class = "btn btn-success" })
</p>

<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Recyclable Type Id</th>
            <th>Description</th>
            <th>Weight</th>
            <th>Computed Rate</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.RecyclableTypeId</td>
                <td>@item.ItemDescription</td>
                <td>@item.Weight</td>
                <td>@item.ComputedRate</td>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-primary btn-sm">Edit</a> |
                    <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SDSExam_Penote/Views/RecyclableItem/_RecyclableItemForm.cshtml
@model SDSExam_Penote.Models.RecyclableItem

@using System.Web.Mvc
@using System.Web.Mvc.Html

<div class="form-group">
    @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.TextBoxFor(model => model.Id, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Id)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.RecyclableTypeId)
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.RecyclableTypeId, (SelectList)ViewBag.RecyclableTypes, "Select Type", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.RecyclableTypeId)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Weight)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.ItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ItemDescription)
    </div>
</div>

@*@section Scripts {
    <script>
        let typeRates = @Html.Raw(Json.Encode(ViewBag.TypeRates));

        function computeRate() {
            let typeId = $('#RecyclableTypeId').val();
            let weight = parseFloat($('#weight').val());
            if (typeId && typeRates[typeId] && !isNaN(weight)) {
                let rate = parseFloat(typeRates[typeId].Rate);
                let min = parseFloat(typeRates[typeId].MinKg);
                let max = parseFloat(typeRates[typeId].MaxKg);
                if (weight < min || weight > max) {
                    alert('Weight must be between ' + min + ' and ' + max);
                    $('#weight').val('');
                    $('#computedRate').val('');
                } else {
                    $('#computedRate').val((weight * rate).toFixed(2));
                }
            }
        }

        $('#RecyclableTypeId, #weight').change(computeRate);
    </script>
}*@