SDSExam_Penote/Controllers/RecyclableItemController.cs
using System.Net;
using System.Web.Mvc;
using SDSExam_Penote.Models;

namespace SDSExam_Penote.Controllers
{
    public class RecyclableItemController : Controller
    {
        private RecyclableItemDAL dal = new RecyclableItemDAL();

        public ActionResult Index()
        {
            return View(dal.GetAll());
        }

        public ActionResult Create()
        {
            var typeDal = new RecyclableTypeDAL();
            var recyclableTypes = typeDal.GetAll();

            ViewBag.RecyclableTypes = new SelectList(recyclableTypes, "Id", "Type");

            var model = new RecyclableItem();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecyclableItem rt)
        {
            if (ModelState.IsValid)
            {
                dal.InsertRecyclableItem(rt);
                return RedirectToAction("Index");
            }

            var typeDal = new RecyclableTypeDAL();
            var recyclableTypes = typeDal.GetAll();
            ViewBag.RecyclableTypes = new SelectList(recyclableTypes, "Id", "Type");

            return View(rt);
        }

        public ActionResult Edit(int id)
        {
            var item = dal.GetById(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            var typeDal = new RecyclableTypeDAL();
            var recyclableTypes = typeDal.GetAll();
            ViewBag.RecyclableTypes = new SelectList(recyclableTypes, "Id", "Type", item.RecyclableTypeId);

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecyclableItem item)
        {
            if (ModelState.IsValid)
            {
                dal.UpdateRecyclableItem(item);
                return RedirectToAction("Index");
            }

            var typeDal = new RecyclableTypeDAL();
            var recyclableTypes = typeDal.GetAll();
            ViewBag.RecyclableTypes = new SelectList(recyclableTypes, "Id", "Type", item.RecyclableTypeId);

            return View(item);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var rt = dal.GetById(id.Value);
            if (rt == null) return HttpNotFound();
            return View(rt);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            dal.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SDSExam_Penote/Controllers/RecyclableTypeController.cs
using System.Net;
using System.Web.Mvc;
using SDSExam_Penote.Models;

namespace SDSExam_Penote.Controllers
{
    public class RecyclableTypeController : Controller
    {
        private RecyclableTypeDAL dal = new RecyclableTypeDAL();

        public ActionResult Index()
        {
            return View(dal.GetAll());
        }

        public ActionResult Create()
        {
            var model = new RecyclableType();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] 
        public ActionResult Create(RecyclableType rt)
        {
            if (ModelState.IsValid)
            {
                dal.Insert(rt);
                return RedirectToAction("Index");
            }
            return View(rt);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var rt = dal.GetById(id.Value);
            if (rt == null) return HttpNotFound();
            return View(rt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecyclableType rt)
        {
            if (ModelState.IsValid)
            {
                dal.Update(rt);
                return RedirectToAction("Index");
            }
            return View(rt);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var rt = dal.GetById(id.Value);
            if (rt == null) return HttpNotFound();
            return View(rt);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            dal.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SDSExam_Penote/Views/RecyclableType/Create.cshtml
@model SDSExam_Penote.Models.RecyclableType

@{
    ViewBag.Title = "Create Recyclable Type";
}

<h2>Create New Recyclable Type</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Type, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinKg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinKg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinKg)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxKg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxKg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxKg)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

SDSExam_Penote/Views/RecyclableType/Delete.cshtml
@model SDSExam_Penote.Models.RecyclableType

@{
    ViewBag.Title = "Delete Recyclable Type";
}

<h2>Delete Recyclable Type</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>Type</dt>
        <dd>@Model.Type</dd>

        <dt>Rate</dt>
        <dd>@Model.Rate</dd>

        <dt>MinKg</dt>
        <dd>@Model.MinKg</dd>

        <dt>MaxKg</dt>
        <dd>@Model.MaxKg</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="submit" value="Delete" class="btn btn-danger" />
        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
    }
</div>

SDSExam_Penote/Views/RecyclableType/Edit.cshtml
@model SDSExam_Penote.Models.RecyclableType

@{
    ViewBag.Title = "Edit Recyclable Type";
}

<h2>Edit Recyclable Type</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true)

        @Html.Partial("_FormFields", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

SDSExam_Penote/Views/RecyclableType/Index.cshtml
@using System.Web.Mvc
@using System.Web.Mvc.Html

@model IEnumerable<SDSExam_Penote.Models.RecyclableType>

@{
    ViewBag.Title = "Recyclable Types";
}

<h2>Recyclable Types</h2>

<p>
    <a href="@Url.Action("Create")" class="btn btn-success">Create New</a>
</p>

<p>
    @Html.ActionLink("Add Recyclable Item", "Create", "RecyclableItem", null, new { @class = "btn btn-success" })
</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Type</th>
            <th>Rate</th>
            <th>MinKg</th>
            <th>MaxKg</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Type</td>
                <td>@item.Rate</td>
                <td>@item.MinKg</td>
                <td>@item.MaxKg</td>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-primary btn-sm">Edit</a> |
                    <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SDSExam_Penote/Views/RecyclableType/_FormFields.cshtml
@model SDSExam_Penote.Models.RecyclableType

@using System.Web.Mvc
@using System.Web.Mvc.Html

<div class="form-group">
    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.TextBoxFor(model => model.Type, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Type)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Rate)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.MinKg, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.MinKg, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MinKg)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.MaxKg, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.MaxKg, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaxKg)
    </div>
</div>